pipeline {
    agent any

    stages {
        stage('Building Project B') {
            steps {
                echo 'Building.. Project B'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing.. Project B'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying.... Project B'
            }
        }
    }
}
